"""Export the ten crate levels (Mrk approved the redone set, 06/10/2026: "triển khai levels 51-60 theo phương án này") to
C#: the layout and COghe's start cell for the editor builder, and the reference route (which crate, and the floor cell
COghe stands on to push or pull it) for the runtime scenario. Reads out_logic/summary_logic.json (levels_logic.py)."""
import json

levels = json.load(open('out_logic/summary_logic.json'))
layouts, routes = [], []
for lv in levels:
    crates = []
    for c in lv['crates_def']:
        ax, az = c['anchor']
        cells = [(ax + dx, az + dz) for dx, dz in c['shape']]
        xs = [x for x, _ in cells]; zs = [z for _, z in cells]
        crates.append((min(xs), min(zs), max(xs) - min(xs) + 1, max(zs) - min(zs) + 1, c['axis'], c['stops'][1] - c['stops'][0], c['red']))
    layouts.append((lv['key'], lv['title'], lv['idea'], tuple(lv['spawn']), crates))
    routes.append((lv['key'], [(m['crate'], m['stand'][0], m['stand'][1]) for m in lv['moves']]))


def cs_bool(b): return 'true' if b else 'false'

ed = ['// Generated by Tools/crate_puzzles/export_unity.py from PLANS/crate-levels-logic (do not edit by hand).',
      'namespace GravityBox.Editor', '{', ' public static partial class VenomCampaignBuilder', ' {',
      '  // Crate levels 51–60: (key, title, lesson, COghe\'s start cell, crates: min cell x, min cell z, cells wide, cells deep,',
      '  // axis, shift in cells, red).',
      '  static readonly (string key,string title,string lesson,(int x,int z) spawn,(int x,int z,int w,int h,char axis,int shift,bool red)[] crates)[] CrateDesigns={']
for key, title, idea, (sx, sz), crates in layouts:
    cs = ','.join(f"({x},{z},{w},{h},'{a}',{d},{cs_bool(r)})" for x, z, w, h, a, d, r in crates)
    ed.append(f'   ("{key}","{title}","{idea}",({sx},{sz}),new[]{{{cs}}}),')
ed += ['  };', ' }', '}']
open('../../Assets/_Game/Editor/COgheSpatialCrateDesigns.cs', 'w').write('\n'.join(ed) + '\n')

rt = ['// Generated by Tools/crate_puzzles/export_unity.py from PLANS/crate-levels-logic (do not edit by hand).',
      '#if UNITY_EDITOR || DEVELOPMENT_BUILD || COGHE_MOBILE_BENCHMARK', 'using System.Collections.Generic;',
      'namespace GravityBox.Venom.ChapterProof', '{',
      ' /// <summary>Reference routes of the crate levels 51–60: each pull names the crate and the floor cell COghe walks to',
      ' /// first (behind the crate to push it, or at its face inside the slide to pull it). Shortest solutions (logic.py).</summary>',
      ' public static class COgheCrateRoutes', ' {',
      '  // The grid on the floor (root space): cell size and the corner of cell (0, 0). Matches VenomCampaignBuilder.CrateGrid.',
      '  public const float Cell=.14f,GridX=-.42f,GridZ=-.35f;',
      '  public static readonly Dictionary<string,(int crate,int x,int z)[]> Steps=new Dictionary<string,(int,int,int)[]>{']
for key, steps in routes:
    rt.append(f'   ["{key}"]=new[]{{{",".join(f"({i},{x},{z})" for i, x, z in steps)}}},')
rt += ['  };', ' }', '}', '#endif']
open('../../Assets/_Game/Venom/Runtime/ChapterProof/COgheCrateRoutes.cs', 'w').write('\n'.join(rt) + '\n')
for (key, _, _, spawn, crates), (_, steps) in zip(layouts, routes):
    print(key, len(crates), 'crates', 'spawn', spawn, len(steps), 'pulls', steps)
