// Generated by Tools/crate_puzzles/export_unity.py from PLANS/crate-levels-logic (do not edit by hand).
namespace GravityBox.Editor
{
 public static partial class VenomCampaignBuilder
 {
  // Crate levels 51–60: (key, title, lesson, COghe's start cell, crates: min cell x, min cell z, cells wide, cells deep,
  // axis, shift in cells, red).
  static readonly (string key,string title,string lesson,(int x,int z) spawn,(int x,int z,int w,int h,char axis,int shift,bool red)[] crates)[] CrateDesigns={
   ("K01","Một thùng chắn","Thùng đỏ trượt được, nhưng một thùng đứng ngay trên đường trượt.",(1,0),new[]{(3,2,2,1,'x',-2,true),(1,1,1,2,'z',2,false),(0,0,1,2,'z',2,false)}),
   ("K02","Chuỗi ba thùng","Thùng chắn thùng đỏ lại bị thùng khác chắn: gỡ từ ngoài vào.",(0,0),new[]{(3,2,1,2,'z',1,true),(1,0,1,2,'z',1,false),(2,3,1,2,'z',-1,false),(3,4,2,1,'x',-3,false)}),
   ("K03","Thùng dài","Thùng dài 3 ô cần một khoảng trống dài mới trượt hết.",(0,0),new[]{(3,2,1,2,'z',-2,true),(2,0,3,1,'x',-2,false),(2,1,1,2,'z',1,false),(3,1,2,1,'x',-3,false)}),
   ("K04","Gỡ từng lớp","Năm thùng chắn nhau thành chuỗi: gỡ đúng thứ tự.",(5,4),new[]{(3,1,1,2,'z',2,true),(2,4,3,1,'x',-2,false),(2,3,2,1,'x',2,false),(5,2,1,2,'z',-1,false),(0,2,1,3,'z',-1,false)}),
   ("K05","Thùng vuông","Thùng vuông lớn; một thùng phải dời đi rồi trả về.",(0,0),new[]{(3,2,2,1,'x',-3,true),(2,0,3,1,'x',1,false),(0,4,2,1,'x',3,false),(2,3,1,2,'z',-1,false),(0,1,2,2,'z',2,false)}),
   ("K06","Dây chuyền","Sáu thùng chắn nhau thành một chuỗi; không lần kéo nào thừa.",(0,0),new[]{(3,2,1,2,'z',-2,true),(0,1,2,2,'z',2,false),(2,0,2,1,'x',2,false),(5,0,1,3,'z',1,false),(4,0,1,2,'z',2,false),(2,1,2,1,'x',-1,false)}),
   ("K07","Mở lối cho COghe","COghe bị thùng vây trong góc: mở lối cho nó trước.",(0,0),new[]{(3,2,2,1,'x',1,true),(3,1,3,1,'x',-2,false),(2,0,2,1,'x',2,false),(0,1,2,2,'z',2,false),(1,4,2,1,'x',1,false),(5,2,1,2,'z',-2,false)}),
   ("K08","Đi rồi trả lại","Hai thùng phải dời tạm rồi trả về chỗ cũ.",(0,4),new[]{(3,2,2,1,'x',1,true),(0,2,2,2,'z',-1,false),(1,4,3,1,'x',1,false),(3,0,3,1,'x',-1,false),(4,1,2,1,'x',-1,false),(5,2,1,2,'z',-2,false)}),
   ("K09","Kho chật","Chín lần kéo; một thùng phải dời qua lại bốn lần.",(5,2),new[]{(3,2,2,1,'x',-3,true),(4,1,2,1,'x',-1,false),(0,1,2,2,'z',-1,false),(1,0,2,1,'x',2,false),(2,3,3,1,'x',1,false),(2,4,2,1,'x',-2,false)}),
   ("K10","Mê cung thùng","Mười lần kéo, bài cuối của bộ.",(0,3),new[]{(3,1,1,2,'z',-1,true),(3,0,2,1,'x',-2,false),(1,4,2,1,'x',2,false),(5,1,1,3,'z',1,false),(0,1,2,2,'z',-1,false),(1,3,2,1,'x',-1,false)}),
  };
 }
}
