// Generated by Tools/crate_puzzles/export_unity.py from PLANS/crate-levels-logic (do not edit by hand).
#if UNITY_EDITOR || DEVELOPMENT_BUILD || COGHE_MOBILE_BENCHMARK
using System.Collections.Generic;
namespace GravityBox.Venom.ChapterProof
{
 /// <summary>Reference routes of the crate levels 51–60: each pull names the crate and the floor cell COghe walks to
 /// first (behind the crate to push it, or at its face inside the slide to pull it). Shortest solutions (logic.py).</summary>
 public static class COgheCrateRoutes
 {
  // The grid on the floor (root space): cell size and the corner of cell (0, 0). Matches VenomCampaignBuilder.CrateGrid.
  public const float Cell=.14f,GridX=-.42f,GridZ=-.35f;
  public static readonly Dictionary<string,(int crate,int x,int z)[]> Steps=new Dictionary<string,(int,int,int)[]>{
   ["K01"]=new[]{(1,1,0),(0,5,2)},
   ["K02"]=new[]{(2,2,2),(3,5,4),(0,3,1)},
   ["K03"]=new[]{(1,5,0),(2,2,3),(3,5,1),(0,3,4)},
   ["K04"]=new[]{(3,5,4),(4,0,1),(1,5,4),(2,1,3),(0,3,0)},
   ["K05"]=new[]{(1,1,0),(3,2,2),(2,2,4),(3,2,1),(4,1,0),(0,5,2)},
   ["K06"]=new[]{(1,1,0),(3,5,3),(4,4,2),(2,1,0),(5,1,1),(0,3,4)},
   ["K07"]=new[]{(2,1,0),(4,3,4),(2,3,0),(3,1,0),(1,2,1),(5,5,4),(0,2,2)},
   ["K08"]=new[]{(2,0,4),(1,1,4),(2,1,4),(1,1,0),(3,2,0),(4,3,1),(5,5,4),(0,2,2)},
   ["K09"]=new[]{(4,1,0),(3,5,2),(4,5,0),(1,4,4),(3,5,0),(4,4,0),(5,2,3),(2,1,0),(0,1,2)},
   ["K10"]=new[]{(1,0,4),(3,1,4),(5,0,3),(1,0,3),(4,1,0),(1,0,4),(5,1,3),(2,5,3),(5,0,3),(0,1,2)},
  };
 }
}
#endif
